# Generated by Django 4.0.5 on 2022-06-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='creaetd',
            new_name='creaeted',
        ),
    ]
